pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            name 'GTNH Maven'
            url 'https://nexus.gtnewhorizons.com/repository/public/'
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

includeBuild('../../common')

rootProject.name = 'BlackBoxPro-Forge-1122'
