modLoader = "kotlinforforge"
loaderVersion = "[5,)"
license = "All-Rights-Reserved"

[[mods]]
modId = "blackboxpro"
version = "${version}"
displayName = "BlackBoxPro NeoForge"
description = "BlackBoxPro client mod for NeoForge 1.21.1."

[[dependencies.blackboxpro]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.blackboxpro]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "CLIENT"
