plugins {
    id 'com.gtnewhorizons.retrofuturagradle' version '1.4.1'
    id 'org.jetbrains.kotlin.jvm' version "${kotlin_version}"
}

def commonJar = file("${rootDir}/../common/build/libs/blackboxpro-common-${project.version}.jar")

archivesBaseName = 'BlackBoxPro-runtime-1.12.2'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

minecraft {
    mcVersion = '1.12.2'
    mcpMappingChannel = 'stable'
    mcpMappingVersion = '39'

    extraRunJvmArguments.addAll('-ea:com.blackboxpro')
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly files(commonJar)
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlin_version}"
    implementation "com.google.code.gson:gson:2.8.9"
}

compileKotlin {
    dependsOn gradle.includedBuild('common').task(':jar')
    kotlinOptions {
        jvmTarget = '1.8'
        freeCompilerArgs = ['-Xjvm-default=all']
    }
}

compileJava {
    dependsOn gradle.includedBuild('common').task(':jar')
}
