modLoader = "kotlinforforge"
loaderVersion = "[5,)"
license = "All-Rights-Reserved"

[[mods]]
modId = "blackboxpro"
version = "${version}"
displayName = "BlackBoxPro NeoForge"
description = "BlackBoxPro client mod for NeoForge."

[[dependencies.blackboxpro]]
modId = "neoforge"
type = "required"
versionRange = "[21.6,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.blackboxpro]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "blackboxpro.mixins.json"
