plugins {
    id 'com.gtnewhorizons.retrofuturagradle' version '1.4.1'
    id 'org.jetbrains.kotlin.jvm' version "${kotlin_version}"
}

// Read version from root project's gradle.properties
def rootProps = new Properties()
rootProps.load(file("${rootDir}/../gradle.properties").newReader())
def rootVersion = rootProps.getProperty('version', '0.0.0')
def embeddedCommon = configurations.create('embeddedCommon')

group = 'com.blackboxpro'
version = rootVersion
archivesBaseName = "BlackBoxPro-forge-1.12.2"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

minecraft {
    mcVersion = '1.12.2'
    mcpMappingChannel = 'stable'
    mcpMappingVersion = '39'

    extraRunJvmArguments.addAll('-ea:com.blackboxpro')
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly "com.blackboxpro:common:${rootVersion}"
    embeddedCommon "com.blackboxpro:common:${rootVersion}"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlin_version}"
    implementation "com.google.code.gson:gson:2.8.9"
}

compileKotlin {
    kotlinOptions {
        jvmTarget = '1.8'
        freeCompilerArgs = ['-Xjvm-default=all']
    }
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', '1.12.2'

    filesMatching('mcmod.info') {
        expand 'version': project.version, 'mcversion': '1.12.2'
    }
}

jar {
    dependsOn gradle.includedBuild('common').task(':jar')
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from {
        configurations.embeddedCommon.collect { zipTree(it) }
    }
    from {
        configurations.runtimeClasspath.findAll { it.name.startsWith('kotlin-') }.collect { zipTree(it) }
    }
}
